version: 1
disable_existing_loggers: false

formatters:
  json:
    format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {extra} | {message}"

handlers:
  console:
    sink: sys.stdout
    level: WARNING
    format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} - {message}"
    colorize: false
  
  file:
    sink: logs/prod.log
    level: INFO
    format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {extra} | {message}"
    rotation: "50 MB"
    retention: "30 days"
    compression: "zip"
  
  sls:
    sink: "sls://prod-project/prod-logstore?region=cn-hangzhou&topic=production&batch_size=500"
    level: INFO
    format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {extra} | {message}"

loggers:
  "":
    level: INFO
    handlers: [console, file, sls]
    propagate: false