version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} - {message}"

handlers:
  console:
    sink: sys.stdout
    level: INFO
    format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} - {message}"
    colorize: true
  
  file:
    sink: logs/dev.log
    level: DEBUG
    format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} - {message}"
    rotation: "1 MB"
    retention: "3 days"

loggers:
  "":
    level: DEBUG
    handlers: [console, file]
    propagate: false