version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} - {message}"
  json:
    format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {extra} | {message}"

handlers:
  console:
    sink: sys.stdout
    level: INFO
    format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} - {message}"
    colorize: true
  
  file:
    sink: logs/app.log
    level: DEBUG
    format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} - {message}"
    rotation: "10 MB"
    retention: "7 days"
    compression: "zip"
  
  sls:
    sink: "sls://demo-project/demo-logstore?region=cn-hangzhou&topic=app&batch_size=100"
    level: INFO
    format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {extra} | {message}"

loggers:
  "":
    level: DEBUG
    handlers: [console, file, sls]
    propagate: false