[tool.uv.workspace]
members = [
    "packages/yai-loguru-sinks",
    "examples/basic-demo",
    "examples/enterprise-demo",
]

[tool.uv]
dev-dependencies = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "black>=23.0.0",
    "ruff>=0.1.0",
    "aliyun-log-python-sdk>=0.7.8",
    "loguru>=0.7.0",
    "loguru-config>=0.1.0",
    "pyyaml>=6.0",
    "python-dotenv>=1.1.1",
]
