# Basic Demo 日志配置
# 基于 loguru-config 的配置格式

handlers:
  # 控制台输出
  - sink: "sys.stdout"
    level: "INFO"
    format: "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {message}"
    colorize: true
    
  # 文件输出
  - sink: "logs/basic-demo.log"
    level: "DEBUG"
    format: "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name}:{function}:{line} - {message}"
    rotation: "10 MB"
    retention: "7 days"
    compression: "zip"