# yai-loguru-sinks 配置示例
# 展示如何使用配置文件驱动的方式配置 SLS sink

handlers:
  # 阿里云 SLS - 错误和警告日志
  - sink: sls://my-project/error-logs?region=cn-hangzhou&topic=python-app&batch_size=50&flush_interval=5.0
    level: ERROR
    format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {message}"
    
  # 阿里云 SLS - 警告日志
  - sink: sls://my-project/warning-logs?region=cn-hangzhou&topic=python-app&batch_size=30&flush_interval=3.0
    level: WARNING
    format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {message}"
    
  # 本地文件 - 调试日志
  - sink: logs/debug.log
    level: DEBUG
    rotation: "1 day"
    retention: "7 days"
    compression: gz
    format: "{time:YYYY-MM-DD HH:mm:ss.SSS} | {level} | {name}:{function}:{line} | {message}"
    
  # 本地文件 - 应用日志
  - sink: logs/app.log
    level: INFO
    rotation: "1 day"
    retention: "30 days"
    compression: gz
    format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {message}"
    
  # 控制台输出 - 开发调试
  - sink: sys.stderr
    level: DEBUG
    format: "<green>{time:HH:mm:ss}</green> | <level>{level}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> | {message}"

# 环境变量说明：
# SLS_ACCESS_KEY_ID: 阿里云访问密钥 ID
# SLS_ACCESS_KEY_SECRET: 阿里云访问密钥 Secret